- name: Install required dependencies
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - fontconfig
      - python3.12-devel
      - python3.12-pip
    state: installed

- name: Create jenkins user
  ansible.builtin.user:
    name: jenkins
    password: $6$gym9nn.unfqHvXZE$P6aU90jotKXbfjcfeb8vnQqp6BFAhD29p1JZs80lqhDLx4cjou1aKOLie04REa2GPpmuhmmPVIPwLrsFCF7vz/

- name: Create jenkins folder
  ansible.builtin.file:
    path: /jenkins
    state: directory
    owner: jenkins
    group: jenkins

- name: Install ansible using pip
  ansible.builtin.pip:
    name:
      - ansible
      - python-jenkins
    executable: pip3.12

- name: Download docker repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Create override directory for docker socket
  ansible.builtin.file:
    path: /etc/systemd/system/docker.socket.d
    state: directory
    mode: '0755'

- name: Set custom socket permissions
  ansible.builtin.copy:
    dest: /etc/systemd/system/docker.socket.d/override.conf
    content: |
      [Socket]
      SocketMode=0666

- name: Enable and start app service
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - docker.socket
    - docker


