- name: Install required dependencies
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - fontconfig
    state: installed

- name: Create jenkins user
  ansible.builtin.user:
    name: jenkins

- name: Create jenkins folder
  ansible.builtin.file:
    path: /jenkins
    state: directory
    owner: jenkins
    group: jenkins

