- name: Install required dependencies
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - fontconfig
    state: installed

- name: Create jenkins user
  ansible.builtin.user:
    name: jenkins
    password: $6$gym9nn.unfqHvXZE$P6aU90jotKXbfjcfeb8vnQqp6BFAhD29p1JZs80lqhDLx4cjou1aKOLie04REa2GPpmuhmmPVIPwLrsFCF7vz/

- name: Create jenkins folder
  ansible.builtin.file:
    path: /jenkins
    state: directory
    owner: jenkins
    group: jenkins

