#wget https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo -O jfrog-artifactory-rpms.repo;
#sudo mv jfrog-artifactory-rpms.repo /etc/yum.repos.d/;
#sudo yum update && sudo yum install jfrog-artifactory-oss

- name: Download artifactory repo
  ansible.builtin.get_url:
    src: https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo
    dest: /etc/yum.repos.d/artifactory-rpms.repo

- name: InstallJFrog artifactory
  ansible.builtin.dnf:
    name: jfrog-artifactory-oss
    state: installed

- name: Start Artifactory
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    enabled: yes


