- name: Copy Jenkins repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install required dependencies
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - fontconfig
    state: installed

- name: Install Jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: installed

- name: Start Jenkins
  ansible.builtin.systemd:
    state: started
    enabled: true


