- name: Copy Jenkins repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install required dependencies
  ansible.builtin.dnf:
    name:
      - java-21-openjdk
      - fontconfig
    state: installed

- name: Install Jenkins
  ansible.builtin.dnf:
    name: jenkins
    state: installed

- name: Ensure Jenkins is stopped before plugin installation
  ansible.builtin.systemd:
    name: jenkins
    state: stopped

- name: Copy plugin list
  ansible.builtin.template:
    src: plugins.txt
    dest: /tmp/plugins.txt

- name: Download plugin CLI
  ansible.builtin.get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.14.0/jenkins-plugin-manager-2.14.0.jar
    dest: /tmp/jenkins-plugin-manager.jar

- name: Copy JCasC config
  ansible.builtin.template:
    src: jenkins.yaml
    dest: /var/lib/jenkins/jenkins.yaml
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Bypass Setup Wizard (Systemd Override)
  ansible.builtin.file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory

- name: Set JAVA_OPTS to skip wizard
  ansible.builtin.copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"

- name: Set JCasC environment variable (systemd override)
  ansible.builtin.copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
      Environment="CASC_JENKINS_CONFIG=/var/lib/jenkins/jenkins.yaml"

- name: Install plugins
  ansible.builtin.command: >
    java -jar /tmp/jenkins-plugin-manager.jar
    --plugin-file /tmp/plugins.txt
    --plugin-download-directory /var/lib/jenkins/plugins

- name: Reload systemd manager (required for env changes)
  ansible.builtin.command: systemctl daemon-reexec

- name: Start Jenkins
  ansible.builtin.systemd_service:
    name: jenkins
    state: restarted
    enabled: true
    daemon_reload: true

- name: Wait for Jenkins to be ready on port 8080
  ansible.builtin.wait_for:
    port: 8080
    delay: 10        # Wait 10 seconds before starting to check
    timeout: 300     # Stop trying after 5 minutes
    state: started